spring:
  application:
    name: duma
  datasource:
    url: jdbc:postgresql://db:5432/duma_db
    username: duma
    password: 163duma
    driver-class-name: org.postgresql.Driver
  mongodb:
      uri: mongodb://duma:163duma@mongodb:27017/duma_db?authSource=admin
  data:
    redis:
      host: redis
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: duma
    password: 163duma
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[hibernate.format_sql]": true

  flyway:
    enabled: true
    locations: classpath:db/migrations
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/duma
          jwk-set-uri: http://keycloak:8080/realms/duma/protocol/openid-connect/certs
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
